// This file contains the shared shark list for all Sharkdle Sharks - Currently 500+ species
// This file is used to populate the shark list in the game and is updated regularly

const sharks = [
            // Cow and Frilled Sharks | Hexanchiformes | Completed
            { "name": "Frilled Shark", "family": "Chlamydoselachidae", "order": "Hexanchiformes", "genus": "Chlamydoselachus", "yod": 1884},
            { "name": "Southern African Frilled Shark", "family": "Chlamydoselachidae", "order": "Hexanchiformes", "genus": "Chlamydoselachus", "yod": 2009},
            { "name": "Sharp Nose Seven Gill Shark", "family": "Hexanchidae", "order": "Hexanchiformes", "genus": "Heptranchias", "yod": 1788},
            { "name": "Blunt Nose Six Gill Shark", "family": "Hexanchidae", "order": "Hexanchiformes", "genus": "Hexanchus", "yod": 1788},
            { "name": "Big Eyed Six Gill Shark", "family": "Hexanchidae", "order": "Hexanchiformes", "genus": "Hexanchus", "yod": 1962},
            { "name": "Atlantic Six Gill Shark", "family": "Hexanchidae", "order": "Hexanchiformes", "genus": "Hexanchus", "yod": 1969},
            { "name": "Broad Nose Seven Gill Shark", "family": "Hexanchidae", "order": "Hexanchiformes", "genus": "Notorynchus", "yod": 1907},
            // DogFish | Squaliformes | Completed
            { "name": "Dwarf Gulper Shark", "family": "Centrophoridae", "order": "Squaliformes", "genus": "Centrophorus", "yod": 1913 },
            { "name": "Gulper Shark", "family": "Centrophoridae", "order": "Squaliformes", "genus": "Centrophorus", "yod": 1801 },
            { "name": "Dumb Gulper Shark", "family": "Centrophoridae", "order": "Squaliformes", "genus": "Centrophorus", "yod": 1915 },
            { "name": "African Gulper Shark", "family": "Centrophoridae", "order": "Squaliformes", "genus": "Centrophorus", "yod": 2017 },
            { "name": "Longfin Gulper Shark", "family": "Centrophoridae", "order": "Squaliformes", "genus": "Centrophorus", "yod": 2017 },
            { "name": "Small-fin Gulper Shark", "family": "Centrophoridae", "order": "Squaliformes", "genus": "Centrophorus", "yod": 1860 },
            { "name": "Seychelles Gulper Shark", "family": "Centrophoridae", "order": "Squaliformes", "genus": "Centrophorus", "yod": 2003 },
            { "name": "Leaf-scale Gulper Shark", "family": "Centrophoridae", "order": "Squaliformes", "genus": "Centrophorus", "yod": 1788 },
            { "name": "Mosaic Gulper Shark", "family": "Centrophoridae", "order": "Squaliformes", "genus": "Centrophorus", "yod": 1906 },
            { "name": "Little Gulper Shark", "family": "Centrophoridae", "order": "Squaliformes", "genus": "Centrophorus", "yod": 1810 },
            { "name": "Western Gulper Shark", "family": "Centrophoridae", "order": "Squaliformes", "genus": "Centrophorus", "yod": 2008 },
            { "name": "Southern Dogfish", "family": "Centrophoridae", "order": "Squaliformes", "genus": "Centrophorus", "yod": 2008 },
            { "name": "Bird-beak Dogfish", "family": "Centrophoridae", "order": "Squaliformes", "genus": "Deania", "yod": 1839 },
            { "name": "Rough Long-nose Dogfish", "family": "Centrophoridae", "order": "Squaliformes", "genus": "Deania", "yod": 1906 },
            { "name": "Arrow-head Dogfish", "family": "Centrophoridae", "order": "Squaliformes", "genus": "Deania", "yod": 1912 },
            { "name": "Long-snout Dogfish", "family": "Centrophoridae", "order": "Squaliformes", "genus": "Deania", "yod": 1915 },
            { "name": "Kite-fin Shark", "family": "Dalatiidae", "order": "Squaliformes", "genus": "Dalatias", "yod": 1788 },
            { "name": "Tail-light Shark", "family": "Dalatiidae", "order": "Squaliformes", "genus": "Euprotomicroides", "yod": 1966 },
            { "name": "Pygmy Shark", "family": "Dalatiidae", "order": "Squaliformes", "genus": "Euprotomicrus", "yod": 1824 },
            { "name": "Long-nose Pygmy Shark", "family": "Dalatiidae", "order": "Squaliformes", "genus": "Heteroscymnoides", "yod": 1934 },
            { "name": "Cookiecutter Shark", "family": "Dalatiidae", "order": "Squaliformes", "genus": "Isistius", "yod": 1824 },
            { "name": "Large-tooth Cookiecutter Shark", "family": "Dalatiidae", "order": "Squaliformes", "genus": "Isistius", "yod": 1964 },
            { "name": "Pocket Shark", "family": "Dalatiidae", "order": "Squaliformes", "genus": "Mollisquama", "yod": 1984 },
            { "name": "American Pocket Shark", "family": "Dalatiidae", "order": "Squaliformes", "genus": "Mollisquama", "yod": 2019 },
            { "name": "Small-eye Pygmy Shark", "family": "Dalatiidae", "order": "Squaliformes", "genus": "Squaliolus", "yod": 1959 },
            { "name": "Spined Pygmy Shark", "family": "Dalatiidae", "order": "Squaliformes", "genus": "Squaliolus", "yod": 1912 },
            { "name": "Bramble Shark", "family": "Echinorhinidae", "order": "Squaliformes", "genus": "Echinorhinus", "yod": 1788 },
            { "name": "Prickly Shark", "family": "Echinorhinidae", "order": "Squaliformes", "genus": "Echinorhinus", "yod": 1928 },
            { "name": "Hook-tooth Dogfish", "family": "Etmopteridae", "order": "Squaliformes", "genus": "Aculeola", "yod": 1959 },
            { "name": "High-fin Dogfish", "family": "Etmopteridae", "order": "Squaliformes", "genus": "Centroscyllium", "yod": 1990 },
            { "name": "Black Dogfish", "family": "Etmopteridae", "order": "Squaliformes", "genus": "Centroscyllium", "yod": 1825 },
            { "name": "Granular Dogfish", "family": "Etmopteridae", "order": "Squaliformes", "genus": "Centroscyllium", "yod": 1887 },
            { "name": "Bare-skin Dogfish", "family": "Etmopteridae", "order": "Squaliformes", "genus": "Centroscyllium", "yod": 1966 },
            { "name": "Comb-tooth Dogfish", "family": "Etmopteridae", "order": "Squaliformes", "genus": "Centroscyllium", "yod": 1899 },
            { "name": "Ornate Dogfish", "family": "Etmopteridae", "order": "Squaliformes", "genus": "Centroscyllium", "yod": 1889 },
            { "name": "White-fin Dogfish", "family": "Etmopteridae", "order": "Squaliformes", "genus": "Centroscyllium", "yod": 1903 },
            { "name": "Whitecheek Lanternshark", "family": "Etmopteridae", "order": "Squaliformes", "genus": "Etmopterus", "yod": 2016 },
            { "name": "New Zealand Lanternshark", "family": "Etmopteridae", "order": "Squaliformes", "genus": "Etmopterus", "yod": 1957 },
            { "name": "Ninja Lanternshark", "family": "Etmopteridae", "order": "Squaliformes", "genus": "Etmopterus", "yod": 2015 },
            { "name": "Blurred Lanternshark", "family": "Etmopteridae", "order": "Squaliformes", "genus": "Etmopterus", "yod": 1993 },
            { "name": "Short-tail Lanternshark", "family": "Etmopteridae", "order": "Squaliformes", "genus": "Etmopterus", "yod": 1912 },
            { "name": "Barrie's Lanternshark", "family": "Etmopteridae", "order": "Squaliformes", "genus": "Etmopterus", "yod": 2021 },
            { "name": "Lined Lanternshark", "family": "Etmopteridae", "order": "Squaliformes", "genus": "Etmopterus", "yod": 1957 },
            { "name": "Broad-snout Lanternshark", "family": "Etmopteridae", "order": "Squaliformes", "genus": "Etmopterus", "yod": 2006 },
            { "name": "Cylindrical Lanternshark", "family": "Etmopteridae", "order": "Squaliformes", "genus": "Etmopterus", "yod": 1985 },
            { "name": "Tail-spot Lanternshark", "family": "Etmopteridae", "order": "Squaliformes", "genus": "Etmopterus", "yod": 2002 },
            { "name": "Compagno's Lanternshark", "family": "Etmopteridae", "order": "Squaliformes", "genus": "Etmopterus", "yod": 1990 },
            { "name": "Comb-tooth Lanternshark", "family": "Etmopteridae", "order": "Squaliformes", "genus": "Etmopterus", "yod": 1966 },
            { "name": "Pink Lanternshark", "family": "Etmopteridae", "order": "Squaliformes", "genus": "Etmopterus", "yod": 2002 },
            { "name": "Black-mouth Lanternshark", "family": "Etmopteridae", "order": "Squaliformes", "genus": "Etmopterus", "yod": 2002 },
            { "name": "Pygmy Lanternshark", "family": "Etmopteridae", "order": "Squaliformes", "genus": "Etmopterus", "yod": 2002 },
            { "name": "Broad-band Lanternshark", "family": "Etmopteridae", "order": "Squaliformes", "genus": "Etmopterus", "yod": 1968 },
            { "name": "Southern Lanternshark", "family": "Etmopteridae", "order": "Squaliformes", "genus": "Etmopterus", "yod": 1880 },
            { "name": "Caribbean Lanternshark", "family": "Etmopteridae", "order": "Squaliformes", "genus": "Etmopterus", "yod": 1861 },
            { "name": "Short-fin Smooth Lanternshark", "family": "Etmopteridae", "order": "Squaliformes", "genus": "Etmopterus", "yod": 2011 },
            { "name": "Laila's Lanternshark", "family": "Etmopteridae", "order": "Squaliformes", "genus": "Etmopterus", "yod": 2017 },
            { "name": "Small-eye Lanternshark", "family": "Etmopteridae", "order": "Squaliformes", "genus": "Etmopterus", "yod": 1990 },
            { "name": "Black-belly Lanternshark", "family": "Etmopteridae", "order": "Squaliformes", "genus": "Etmopterus", "yod": 1902 },
            { "name": "Marsha's Lanternshark", "family": "Etmopteridae", "order": "Squaliformes", "genus": "Etmopterus", "yod": 2018 },
            { "name": "Moller's Lanternshark", "family": "Etmopteridae", "order": "Squaliformes", "genus": "Etmopterus", "yod": 1939 },
            { "name": "Dwarf Lanternshark", "family": "Etmopteridae", "order": "Squaliformes", "genus": "Etmopterus", "yod": 1985 },
            { "name": "African Lanternshark", "family": "Etmopteridae", "order": "Squaliformes", "genus": "Etmopterus", "yod": 1953 },
            { "name": "Great Lanternshark", "family": "Etmopteridae", "order": "Squaliformes", "genus": "Etmopterus", "yod": 1904 },
            { "name": "False Lanternshark", "family": "Etmopteridae", "order": "Squaliformes", "genus": "Etmopterus", "yod": 2002 },
            { "name": "Smooth Lanternshark", "family": "Etmopteridae", "order": "Squaliformes", "genus": "Etmopterus", "yod": 1839 },
            { "name": "Dense-scale Lanternshark", "family": "Etmopteridae", "order": "Squaliformes", "genus": "Etmopterus", "yod": 1990 },
            { "name": "West Indian Lanternshark", "family": "Etmopteridae", "order": "Squaliformes", "genus": "Etmopterus", "yod": 1997 },
            { "name": "Papuan Lanternshark", "family": "Etmopteridae", "order": "Squaliformes", "genus": "Etmopterus", "yod": 2017 },
            { "name": "Fringe-fin Lanternshark", "family": "Etmopteridae", "order": "Squaliformes", "genus": "Etmopterus", "yod": 1953 },
            { "name": "Sculpted Lanternshark", "family": "Etmopteridae", "order": "Squaliformes", "genus": "Etmopterus", "yod": 2011 },
            { "name": "Thorny Lanternshark", "family": "Etmopteridae", "order": "Squaliformes", "genus": "Etmopterus", "yod": 1976 },
            { "name": "Rasp-tooth Dogfish", "family": "Etmopteridae", "order": "Squaliformes", "genus": "Etmopterus", "yod": 1986 },
            { "name": "Velvet-belly Lanternshark", "family": "Etmopteridae", "order": "Squaliformes", "genus": "Etmopterus", "yod": 1758 },
            { "name": "Splendid Lanternshark", "family": "Etmopteridae", "order": "Squaliformes", "genus": "Etmopterus", "yod": 1988 },
            { "name": "Bristled Lanternshark", "family": "Etmopteridae", "order": "Squaliformes", "genus": "Etmopterus", "yod": 1912 },
            { "name": "Traveller Lanternshark", "family": "Etmopteridae", "order": "Squaliformes", "genus": "Etmopterus", "yod": 2011 },
            { "name": "Hawaiian Lanternshark", "family": "Etmopteridae", "order": "Squaliformes", "genus": "Etmopterus", "yod": 1905 },
            { "name": "Green Lanternshark", "family": "Etmopteridae", "order": "Squaliformes", "genus": "Etmopterus", "yod": 1953 },
            { "name": "Viper Dogfish", "family": "Etmopteridae", "order": "Squaliformes", "genus": "Trigonognathus", "yod": 1990 },
            { "name": "Prickly Dogfish", "family": "Oxynotidae", "order": "Squaliformes", "genus": "Oxynotus", "yod": 1893 },
            { "name": "Caribbean Roughshark", "family": "Oxynotidae", "order": "Squaliformes", "genus": "Oxynotus", "yod": 1961 },
            { "name": "Angular Roughshark", "family": "Oxynotidae", "order": "Squaliformes", "genus": "Oxynotus", "yod": 1758 },
            { "name": "Japanese Roughshark", "family": "Oxynotidae", "order": "Squaliformes", "genus": "Oxynotus", "yod": 1985 },
            { "name": "Sail-fin Roughshark", "family": "Oxynotidae", "order": "Squaliformes", "genus": "Oxynotus", "yod": 1929 },
            { "name": "Portuguese Dogfish", "family": "Somniosidae", "order": "Squaliformes", "genus": "Centroscymnus", "yod": 1864 },
            { "name": "Rough-skin Dogfish", "family": "Somniosidae", "order": "Squaliformes", "genus": "Centroscymnus", "yod": 1906 },
            { "name": "Long-nose Velvet Dogfish", "family": "Somniosidae", "order": "Squaliformes", "genus": "Centroselachus", "yod": 1864 },
            { "name": "White-tail Dogfish", "family": "Somniosidae", "order": "Squaliformes", "genus": "Scymnodalatias", "yod": 1986 },
            { "name": "Azores Dogfish", "family": "Somniosidae", "order": "Squaliformes", "genus": "Scymnodalatias", "yod": 1988 },
            { "name": "Sparse-tooth Dogfish", "family": "Somniosidae", "order": "Squaliformes", "genus": "Scymnodalatias", "yod": 1988 },
            { "name": "Sherwood's Dogfish", "family": "Somniosidae", "order": "Squaliformes", "genus": "Scymnodalatias", "yod": 1921 },
            { "name": "Japanese Velvet Dogfish", "family": "Somniosidae", "order": "Squaliformes", "genus": "Scymnodon", "yod": 1984 },
            { "name": "Large-spine Velvet Dogfish", "family": "Somniosidae", "order": "Squaliformes", "genus": "Scymnodon", "yod": 1906 },
            { "name": "Plunket Shark", "family": "Somniosidae", "order": "Squaliformes", "genus": "Scymnodon", "yod": 1910 },
            { "name": "Knife-tooth Dogfish", "family": "Somniosidae", "order": "Squaliformes", "genus": "Scymnodon", "yod": 1864 },
            { "name": "Southern Sleeper Shark", "family": "Somniosidae", "order": "Squaliformes", "genus": "Somniosus", "yod": 1939 },
            { "name": "Taiwan Sleeper Shark", "family": "Somniosidae", "order": "Squaliformes", "genus": "Somniosus", "yod": 2020 },
            { "name": "Frog Shark", "family": "Somniosidae", "order": "Squaliformes", "genus": "Somniosus", "yod": 1912 },
            { "name": "Greenland Shark", "family": "Somniosidae", "order": "Squaliformes", "genus": "Somniosus", "yod": 1801 },
            { "name": "Pacific Sleeper Shark", "family": "Somniosidae", "order": "Squaliformes", "genus": "Somniosus", "yod": 1944 },
            { "name": "Little Sleeper Shark", "family": "Somniosidae", "order": "Squaliformes", "genus": "Somniosus", "yod": 1827 },
            { "name": "Velvet Dogfish", "family": "Somniosidae", "order": "Squaliformes", "genus": "Zameus", "yod": 1877 },
            { "name": "Rough-skin Spurdog", "family": "Squalidae", "order": "Squaliformes", "genus": "Cirrhigaleus", "yod": 1973 },
            { "name": "Southern Mandarin Dogfish", "family": "Squalidae", "order": "Squaliformes", "genus": "Cirrhigaleus", "yod": 2007 },
            { "name": "Mandarin Dogfish", "family": "Squalidae", "order": "Squaliformes", "genus": "Cirrhigaleus", "yod": 1912 },
            { "name": "Spiny Dogfish", "family": "Squalidae", "order": "Squaliformes", "genus": "Squalus", "yod": 1758 },
            { "name": "Blunt-nose Spiny Dogfish", "family": "Squalidae", "order": "Squaliformes", "genus": "Squalus", "yod": 1908 },
            { "name": "Brazilian Whitetail Dogfish", "family": "Squalidae", "order": "Squaliformes", "genus": "Squalus", "yod": 2016 },
            { "name": "Eastern High-fin Spurdog", "family": "Squalidae", "order": "Squaliformes", "genus": "Squalus", "yod": 2007 },
            { "name": "Western High-fin Spurdog", "family": "Squalidae", "order": "Squaliformes", "genus": "Squalus", "yod": 2007 },
            { "name": "Northeastern Brazilian Dogfish", "family": "Squalidae", "order": "Squaliformes", "genus": "Squalus", "yod": 2016 },
            { "name": "Long-nosed African Spurdog", "family": "Squalidae", "order": "Squaliformes", "genus": "Squalus", "yod": 2017 },
            { "name": "Long-nose Spurdog", "family": "Squalidae", "order": "Squaliformes", "genus": "Squalus", "yod": 1827 },
            { "name": "Japanese Short-nose Spurdog", "family": "Squalidae", "order": "Squaliformes", "genus": "Squalus", "yod": 1917 },
            { "name": "Big-head Spurdog", "family": "Squalidae", "order": "Squaliformes", "genus": "Squalus", "yod": 2007 },
            { "name": "Green-eye Spurdog", "family": "Squalidae", "order": "Squaliformes", "genus": "Squalus", "yod": 2007 },
            { "name": "Gulf Dogfish", "family": "Squalidae", "order": "Squaliformes", "genus": "Squalus", "yod": 2018 },
            { "name": "Fat-spine Spurdog", "family": "Squalidae", "order": "Squaliformes", "genus": "Squalus", "yod": 2007 },
            { "name": "Cuban Dogfish", "family": "Squalidae", "order": "Squaliformes", "genus": "Squalus", "yod": 1936 },
            { "name": "Edmund's Spurdog", "family": "Squalidae", "order": "Squaliformes", "genus": "Squalus", "yod": 2007 },
            { "name": "Taiwan Spurdog", "family": "Squalidae", "order": "Squaliformes", "genus": "Squalus", "yod": 2011 },
            { "name": "Eastern Long-nose Spurdog", "family": "Squalidae", "order": "Squaliformes", "genus": "Squalus", "yod": 2007 },
            { "name": "Northern Spiny Dogfish", "family": "Squalidae", "order": "Squaliformes", "genus": "Squalus", "yod": 1931 },
            { "name": "Hawaiian Dogfish", "family": "Squalidae", "order": "Squaliformes", "genus": "Squalus", "yod": 2018 },
            { "name": "Indonesian Short-snout Spurdog", "family": "Squalidae", "order": "Squaliformes", "genus": "Squalus", "yod": 2007 },
            { "name": "Japanese Spurdog", "family": "Squalidae", "order": "Squaliformes", "genus": "Squalus", "yod": 1908 },
            { "name": "Seychelles Spurdog", "family": "Squalidae", "order": "Squaliformes", "genus": "Squalus", "yod": 2003 },
            { "name": "Atlantic Lobefin Dogfish", "family": "Squalidae", "order": "Squaliformes", "genus": "Squalus", "yod": 2016 },
            { "name": "Malagasy Skinny Spurdog", "family": "Squalidae", "order": "Squaliformes", "genus": "Squalus", "yod": 2017 },
            { "name": "Smith's Dogfish", "family": "Squalidae", "order": "Squaliformes", "genus": "Squalus", "yod": 2017 },
            { "name": "Short-nose Spurdog", "family": "Squalidae", "order": "Squaliformes", "genus": "Squalus", "yod": 1881 },
            { "name": "Black-tailed Spurdog", "family": "Squalidae", "order": "Squaliformes", "genus": "Squalus", "yod": 1979 },
            { "name": "Short-spine Spurdog", "family": "Squalidae", "order": "Squaliformes", "genus": "Squalus", "yod": 1903 },
            { "name": "Indonesian Greeneye Spurdog", "family": "Squalidae", "order": "Squaliformes", "genus": "Squalus", "yod": 1931 },
            { "name": "Western Long-nose Spurdog", "family": "Squalidae", "order": "Squaliformes", "genus": "Squalus", "yod": 2007 },
            { "name": "Bar-tail Spurdog", "family": "Squalidae", "order": "Squaliformes", "genus": "Squalus", "yod": 2007 },
            { "name": "Humpback Dogfish", "family": "Squalidae", "order": "Squaliformes", "genus": "Squalus", "yod": 2016 },
            { "name": "Cyrano Spurdog", "family": "Squalidae", "order": "Squaliformes", "genus": "Squalus", "yod": 1979 },
            { "name": "Kermadec Spiny Dogfish", "family": "Squalidae", "order": "Squaliformes", "genus": "Squalus", "yod": 2007 },
            { "name": "Shirai's Spurdog", "family": "Squalidae", "order": "Squaliformes", "genus": "Squalus", "yod": 2020 },
            { "name": "Pacific Spiny Dogfish", "family": "Squalidae", "order": "Squaliformes", "genus": "Squalus", "yod": 1854 },
            // Saw Sharks | Pristiophoriformes | Completed
            { "name": "Annas Six Gill Saw Shark", "family": "Pristiophoridae", "order": "Pristiophoriformes", "genus": "Pliotrema", "yod": 2020},
            { "name": "Kajas Six Gill Saw Shark", "family": "Pristiophoridae", "order": "Pristiophoriformes", "genus": "Pliotrema", "yod": 2020},
            { "name": "Six Gill Saw Shark", "family": "Pristiophoridae", "order": "Pristiophoriformes", "genus": "Pliotrema", "yod": 1906},
            { "name": "Long Nose Saw Shark", "family": "Pristiophoridae", "order": "Pristiophoriformes", "genus": "Pristiophorus", "yod": 1794},
            { "name": "Short Nose Saw Shark", "family": "Pristiophoridae", "order": "Pristiophoriformes", "genus": "Pristiophorus", "yod": 1870},
            { "name": "Japanese Saw Shark", "family": "Pristiophoridae", "order": "Pristiophoriformes", "genus": "Pristiophorus", "yod": 1870},
            { "name": "Bahamas Saw Shark", "family": "Pristiophoridae", "order": "Pristiophoriformes", "genus": "Pristiophorus", "yod": 1960},
            { "name": "African Saw Shark", "family": "Pristiophoridae", "order": "Pristiophoriformes", "genus": "Pristiophorus", "yod": 1960},
            { "name": "Tropical Saw Shark","family": "Pristiophoridae", "order": "Pristiophoriformes", "genus": "Pristiophorus", "yod": 2008},
            { "name": "Lanas Saw Shark","family": "Pristiophoridae", "order": "Pristiophoriformes", "genus": "Pristiophorus", "yod": 2013},
            { "name": "African Dwarf Saw Shark","family": "Pristiophoridae", "order": "Pristiophoriformes", "genus": "Pristiophorus", "yod": 2011},
            // Angel Sharks | Squantiniformes | Completed
            { "name": "Eastern Angel Shark", "family": "Squatinidae", "order": "Squantiniformes", "genus": "Squatina Albipunctata", "yod": 2008},
            { "name": "African Angel Shark", "family": "Squatinidae", "order": "Squantiniformes", "genus": "Squatina Albipunctata", "yod": 1908},
            { "name": "Atlantic Angel Shark", "family": "Squatinidae", "order": "Squantiniformes", "genus": "Squatina Albipunctata", "yod": 1818},
            { "name": "Short Crested Angel Shark", "family": "Squatinidae", "order": "Squantiniformes", "genus": "Squatina Albipunctata", "yod": 2021},
            { "name": "Clouded Angel Shark", "family": "Squatinidae", "order": "Squantiniformes", "genus": "Squatina Albipunctata", "yod": 1906},
            { "name": "Hidden Angel Shark", "family": "Squatinidae", "order": "Squantiniformes", "genus": "Squatina Albipunctata", "yod": 1992},
            { "name": "Angel Shark", "family": "Squatinidae", "order": "Squantiniformes", "genus": "Squatina Albipunctata", "yod": 1758},
            { "name": "Saw Back Angel Shark","family": "Squatinidae", "order": "Squantiniformes", "genus": "Squatina Albipunctata", "yod": 1829},
            { "name": "Argentine Angel Shark","family": "Squatinidae", "order": "Squantiniformes", "genus": "Squatina Albipunctata", "yod": 1930},
            { "name": "Chilean Angel Shark","family": "Squatinidae", "order": "Squantiniformes", "genus": "Squatina Albipunctata", "yod": 1887},
            { "name": "Australian Angel Shark","family": "Squatinidae", "order": "Squantiniformes", "genus": "Squatina Albipunctata", "yod": 1906},
            { "name": "Philippines Angel Shark","family": "Squatinidae", "order": "Squantiniformes", "genus": "Squatina Albipunctata", "yod": 2011},
            { "name": "Pacific Angel Shark","family": "Squatinidae", "order": "Squantiniformes", "genus": "Squatina Albipunctata", "yod": 1859},
            { "name": "Davids Angel Shark","family": "Squatinidae", "order": "Squantiniformes", "genus": "Squatina Albipunctata", "yod": 2016},
            { "name": "Taiwan Angel Shark","family": "Squatinidae", "order": "Squantiniformes", "genus": "Squatina Albipunctata", "yod": 1972},
            { "name": "Angular Angel Shark","family": "Squatinidae", "order": "Squantiniformes", "genus": "Squatina Albipunctata", "yod": 1936},
            { "name": "Disparate Angel Shark","family": "Squatinidae", "order": "Squantiniformes", "genus": "Squatina Albipunctata", "yod": 2007},
            { "name": "Japanese Angel Shark","family": "Squatinidae", "order": "Squantiniformes", "genus": "Squatina Albipunctata", "yod": 1858},
            { "name": "Leas Angel Shark","family": "Squatinidae", "order": "Squantiniformes", "genus": "Squatina Albipunctata", "yod": 2023},
            { "name": "Indonesian Angel Shark","family": "Squatinidae", "order": "Squantiniformes", "genus": "Squatina Albipunctata", "yod": 2008},
            { "name": "Short Crested Angel Shark","family": "Squatinidae", "order": "Squantiniformes", "genus": "Squatina Albipunctata", "yod": 2021},
            { "name": "Mexican Angel Shark","family": "Squatinidae", "order": "Squantiniformes", "genus": "Squatina Albipunctata", "yod": 2007},
            { "name": "SmoothBack Angel Shark","family": "Squatinidae", "order": "Squantiniformes", "genus": "Squatina Albipunctata", "yod": 1840},
            { "name": "Western Angel Shark","family": "Squatinidae", "order": "Squantiniformes", "genus": "Squatina Albipunctata", "yod": 2008},
            { "name": "Ornate Angel Shark","family": "Squatinidae", "order": "Squantiniformes", "genus": "Squatina Albipunctata", "yod": 1914},
            { "name": "Ocellated Angel Shark","family": "Squatinidae", "order": "Squantiniformes", "genus": "Squatina Albipunctata", "yod": 1963},
            { "name": "Varis Angel Shark","family": "Squatinidae", "order": "Squantiniformes", "genus": "Squatina Albipunctata", "yod": 2018},
            // BullHead Sharks | Heterodontiformes | Completed
            { "name": "Horn Shark", "family": "Heterodontidae", "order": "Heterodontiformes", "genus": "Heterodontus", "yod": 1855 },
            { "name": "Crested Bullhead Shark", "family": "Heterodontidae", "order": "Heterodontiformes", "genus": "Heterodontus", "yod": 1870 },
            { "name": "Japanese Bullhead Shark", "family": "Heterodontidae", "order": "Heterodontiformes", "genus": "Heterodontus", "yod": 1884 },
            { "name": "Painted Hornshark", "family": "Heterodontidae", "order": "Heterodontiformes", "genus": "Heterodontus", "yod": 2023 },
            { "name": "Mexican Hornshark", "family": "Heterodontidae", "order": "Heterodontiformes", "genus": "Heterodontus", "yod": 1972 },
            { "name": "Oman Bullhead Shark", "family": "Heterodontidae", "order": "Heterodontiformes", "genus": "Heterodontus", "yod": 2005 },
            { "name": "Port Jackson Shark", "family": "Heterodontidae", "order": "Heterodontiformes", "genus": "Heterodontus", "yod": 1793 },
            { "name": "Galapagos Bullhead Shark", "family": "Heterodontidae", "order": "Heterodontiformes", "genus": "Heterodontus", "yod": 1840 },
            { "name": "White-spotted Bullhead Shark", "family": "Heterodontidae", "order": "Heterodontiformes", "genus": "Heterodontus", "yod": 1949 },
            { "name": "Zebra Bullhead Shark", "family": "Heterodontidae", "order": "Heterodontiformes", "genus": "Heterodontus", "yod": 1831 },
            // Mackerel Sharks | Lamniformes | Completed
            { "name": "Pelagic Thresher Shark", "family": "Alopiidae", "order": "Lamniformes", "genus": "Alopias", "yod": 1935 },
            { "name": "Big-eye Thresher Shark", "family": "Alopiidae", "order": "Lamniformes", "genus": "Alopias", "yod": 1841 },
            { "name": "Thresher Shark", "family": "Alopiidae", "order": "Lamniformes", "genus": "Alopias", "yod": 1788 },
            { "name": "Basking Shark", "family": "Cetorhinidae", "order": "Lamniformes", "genus": "Cetorhinus", "yod": 1765 },
            { "name": "Great White Shark", "family": "Lamnidae", "order": "Lamniformes", "genus": "Carcharodon", "yod": 1758 },
            { "name": "Short-fin Mako", "family": "Lamnidae", "order": "Lamniformes", "genus": "Isurus", "yod": 1810 },
            { "name": "Long-fin Mako", "family": "Lamnidae", "order": "Lamniformes", "genus": "Isurus", "yod": 1966 },
            { "name": "Salmon Shark", "family": "Lamnidae", "order": "Lamniformes", "genus": "Lamna", "yod": 1947 },
            { "name": "Porbeagle Shark", "family": "Lamnidae", "order": "Lamniformes", "genus": "Lamna", "yod": 1788 },
            { "name": "Megamouth Shark", "family": "Megachasmidae", "order": "Lamniformes", "genus": "Megachasma", "yod": 1983 },
            { "name": "Goblin Shark", "family": "Mitsukurinidae", "order": "Lamniformes", "genus": "Mitsukurina", "yod": 1898 },
            { "name": "Sand Tiger Shark", "family": "Odontaspididae", "order": "Lamniformes", "genus": "Carcharias", "yod": 1810 },
            { "name": "Small-tooth Sandtiger Shark", "family": "Odontaspididae", "order": "Lamniformes", "genus": "Odontaspis", "yod": 1810 },
            { "name": "Big-eye Sand Tiger Shark", "family": "Odontaspididae", "order": "Lamniformes", "genus": "Odontaspis", "yod": 1955 },
            { "name": "Crocodile Shark", "family": "Pseudocarchariidae", "order": "Lamniformes", "genus": "Pseudocarcharias", "yod": 1936 },
            // Carpet Sharks | Orectolobiformes | Completed
            { "name": "Blue-grey Carpetshark", "family": "Brachaeluridae", "order": "Orectolobiformes", "genus": "Brachaelurus", "yod": 1908 },
            { "name": "Blind Shark", "family": "Brachaeluridae", "order": "Orectolobiformes", "genus": "Brachaelurus", "yod": 1801 },
            { "name": "Nurse Shark", "family": "Ginglymostomatidae", "order": "Orectolobiformes", "genus": "Ginglymostoma", "yod": 1788 },
            { "name": "Pacific Nurse Shark", "family": "Ginglymostomatidae", "order": "Orectolobiformes", "genus": "Ginglymostoma", "yod": 2015 },
            { "name": "Tawny Nurse Shark", "family": "Ginglymostomatidae", "order": "Orectolobiformes", "genus": "Nebrius", "yod": 1831 },
            { "name": "Short-tail Nurse Shark", "family": "Ginglymostomatidae", "order": "Orectolobiformes", "genus": "Pseudoginglymostoma", "yod": 1867 },
            { "name": "Arabian Carpetshark", "family": "Hemiscylliidae", "order": "Orectolobiformes", "genus": "Chiloscyllium", "yod": 1980 },
            { "name": "Burmese Bamboo Shark", "family": "Hemiscylliidae", "order": "Orectolobiformes", "genus": "Chiloscyllium", "yod": 1983 },
            { "name": "Grey Bamboo Shark", "family": "Hemiscylliidae", "order": "Orectolobiformes", "genus": "Chiloscyllium", "yod": 1838 },
            { "name": "Hasselt's Bamboo Shark", "family": "Hemiscylliidae", "order": "Orectolobiformes", "genus": "Chiloscyllium", "yod": 1852 },
            { "name": "Slender Bamboo Shark", "family": "Hemiscylliidae", "order": "Orectolobiformes", "genus": "Chiloscyllium", "yod": 1789 },
            { "name": "White-spotted Bamboo Shark", "family": "Hemiscylliidae", "order": "Orectolobiformes", "genus": "Chiloscyllium", "yod": 1830 },
            { "name": "Brown-banded Bamboo Shark", "family": "Hemiscylliidae", "order": "Orectolobiformes", "genus": "Chiloscyllium", "yod": 1838 },
            { "name": "Indonesian Speckled Carpetshark", "family": "Hemiscylliidae", "order": "Orectolobiformes", "genus": "Hemiscyllium", "yod": 1824 },
            { "name": "Cenderawasih Epaulette Shark", "family": "Hemiscylliidae", "order": "Orectolobiformes", "genus": "Hemiscyllium", "yod": 2008 },
            { "name": "Papuan Epaulette Shark", "family": "Hemiscylliidae", "order": "Orectolobiformes", "genus": "Hemiscyllium", "yod": 1967 },
            { "name": "Halmahera Epaulette Shark", "family": "Hemiscylliidae", "order": "Orectolobiformes", "genus": "Hemiscyllium", "yod": 2013 },
            { "name": "Triton Epaulette Shark", "family": "Hemiscylliidae", "order": "Orectolobiformes", "genus": "Hemiscyllium", "yod": 2008 },
            { "name": "Leopard Epaulette Shark", "family": "Hemiscylliidae", "order": "Orectolobiformes", "genus": "Hemiscyllium", "yod": 2010 },
            { "name": "Epaulette Shark", "family": "Hemiscylliidae", "order": "Orectolobiformes", "genus": "Hemiscyllium", "yod": 1788 },
            { "name": "Hooded Carpetshark", "family": "Hemiscylliidae", "order": "Orectolobiformes", "genus": "Hemiscyllium", "yod": 1967 },
            { "name": "Speckled Carpetshark", "family": "Hemiscylliidae", "order": "Orectolobiformes", "genus": "Hemiscyllium", "yod": 1843 },
            { "name": "Tasselled Wobbegong", "family": "Orectolobidae", "order": "Orectolobiformes", "genus": "Eucrossorhinus", "yod": 1867 },
            { "name": "Floral Banded Wobbegong", "family": "Orectolobidae", "order": "Orectolobiformes", "genus": "Orectolobus", "yod": 2008 },
            { "name": "Banded Wobbegong", "family": "Orectolobidae", "order": "Orectolobiformes", "genus": "Orectolobus", "yod": 1940 },
            { "name": "Western Wobbegong", "family": "Orectolobidae", "order": "Orectolobiformes", "genus": "Orectolobus", "yod": 2006 },
            { "name": "Japanese Wobbegong", "family": "Orectolobidae", "order": "Orectolobiformes", "genus": "Orectolobus", "yod": 1906 },
            { "name": "Indonesian Wobbegong", "family": "Orectolobidae", "order": "Orectolobiformes", "genus": "Orectolobus", "yod": 2010 },
            { "name": "Spotted Wobbegong", "family": "Orectolobidae", "order": "Orectolobiformes", "genus": "Orectolobus", "yod": 1788 },
            { "name": "Ornate Wobbegong", "family": "Orectolobidae", "order": "Orectolobiformes", "genus": "Orectolobus", "yod": 1883 },
            { "name": "Dwarf Spotted Wobbegong", "family": "Orectolobidae", "order": "Orectolobiformes", "genus": "Orectolobus", "yod": 2008 },
            { "name": "Network Wobbegong", "family": "Orectolobidae", "order": "Orectolobiformes", "genus": "Orectolobus", "yod": 2008 },
            { "name": "Northern Wobbegong", "family": "Orectolobidae", "order": "Orectolobiformes", "genus": "Orectolobus", "yod": 1939 },
            { "name": "Cobbler Wobbegong", "family": "Orectolobidae", "order": "Orectolobiformes", "genus": "Sutorectus", "yod": 1864 },
            { "name": "Barbel-throat Carpetshark", "family": "Parascylliidae", "order": "Orectolobiformes", "genus": "Cirrhoscyllium", "yod": 1913 },
            { "name": "Taiwan Saddled Carpetshark", "family": "Parascylliidae", "order": "Orectolobiformes", "genus": "Cirrhoscyllium", "yod": 1959 },
            { "name": "Saddle Carpetshark", "family": "Parascylliidae", "order": "Orectolobiformes", "genus": "Cirrhoscyllium", "yod": 1943 },
            { "name": "Collared Carpetshark", "family": "Parascylliidae", "order": "Orectolobiformes", "genus": "Parascyllium", "yod": 1888 },
            { "name": "Elongated Carpetshark", "family": "Parascylliidae", "order": "Orectolobiformes", "genus": "Parascyllium", "yod": 2008 },
            { "name": "Rusty Carpetshark", "family": "Parascylliidae", "order": "Orectolobiformes", "genus": "Parascyllium", "yod": 1911 },
            { "name": "Ginger Carpetshark", "family": "Parascylliidae", "order": "Orectolobiformes", "genus": "Parascyllium", "yod": 2002 },
            { "name": "Necklace Carpetshark", "family": "Parascylliidae", "order": "Orectolobiformes", "genus": "Parascyllium", "yod": 1853 },
            { "name": "Whale Shark", "family": "Rhincodontidae", "order": "Orectolobiformes", "genus": "Rhincodon", "yod": 1828 },
            { "name": "Zebra Shark", "family": "Stegostomatidae", "order": "Orectolobiformes", "genus": "Stegostoma", "yod": 1783 },
            // Ground Sharks | Carcharhiniformes
            { "name": "Blacknose Shark", "family": "Carcharhinidae", "order": "Carcharhiniformes", "genus": "Carcharhinus", "yod": 1860 },
            { "name": "Silvertip Shark", "family": "Carcharhinidae", "order": "Carcharhiniformes", "genus": "Carcharhinus", "yod": 1837 },
            { "name": "Bignose Shark", "family": "Carcharhinidae", "order": "Carcharhiniformes", "genus": "Carcharhinus", "yod": 1950 },
            { "name": "Graceful Shark", "family": "Carcharhinidae", "order": "Carcharhiniformes", "genus": "Carcharhinus", "yod": 1934 },
            { "name": "Grey Reef Shark", "family": "Carcharhinidae", "order": "Carcharhiniformes", "genus": "Carcharhinus", "yod": 1856 },
            { "name": "Pigeye Shark", "family": "Carcharhinidae", "order": "Carcharhiniformes", "genus": "Carcharhinus", "yod": 1839 },
            { "name": "Borneo Shark", "family": "Carcharhinidae", "order": "Carcharhiniformes", "genus": "Carcharhinus", "yod": 1858 },
            { "name": "Copper Shark", "family": "Carcharhinidae", "order": "Carcharhiniformes", "genus": "Carcharhinus", "yod": 1870 },
            { "name": "Spinner Shark", "family": "Carcharhinidae", "order": "Carcharhiniformes", "genus": "Carcharhinus", "yod": 1839 },
            { "name": "Nervous Shark", "family": "Carcharhinidae", "order": "Carcharhiniformes", "genus": "Carcharhinus", "yod": 1945 },
            { "name": "Pacific Smalltail Shark", "family": "Carcharhinidae", "order": "Carcharhiniformes", "genus": "Carcharhinus", "yod": 1898 },
            { "name": "Coates' Shark", "family": "Carcharhinidae", "order": "Carcharhiniformes", "genus": "Carcharhinus", "yod": 1939 },
            { "name": "Whitecheek Shark", "family": "Carcharhinidae", "order": "Carcharhiniformes", "genus": "Carcharhinus", "yod": 1839 },
            { "name": "Silky Shark", "family": "Carcharhinidae", "order": "Carcharhiniformes", "genus": "Carcharhinus", "yod": 1839 },
            { "name": "Creek Whaler", "family": "Carcharhinidae", "order": "Carcharhiniformes", "genus": "Carcharhinus", "yod": 1943 },
            { "name": "Galapagos Shark", "family": "Carcharhinidae", "order": "Carcharhiniformes", "genus": "Carcharhinus", "yod": 1905 },
            { "name": "Pondicherry Shark", "family": "Carcharhinidae", "order": "Carcharhiniformes", "genus": "Carcharhinus", "yod": 1839 },
            { "name": "Human's Whaler Shark", "family": "Carcharhinidae", "order": "Carcharhiniformes", "genus": "Carcharhinus", "yod": 2014 },
            { "name": "Finetooth Shark", "family": "Carcharhinidae", "order": "Carcharhiniformes", "genus": "Carcharhinus", "yod": 1839 },
            { "name": "Smooth Tooth Blacktip Shark", "family": "Carcharhinidae", "order": "Carcharhiniformes", "genus": "Carcharhinus", "yod": 1985 },
            { "name": "Bull Shark", "family": "Carcharhinidae", "order": "Carcharhiniformes", "genus": "Carcharhinus", "yod": 1839 },
            { "name": "Blacktip Shark", "family": "Carcharhinidae", "order": "Carcharhiniformes", "genus": "Carcharhinus", "yod": 1839 },
            { "name": "Oceanic Whitetip Shark", "family": "Carcharhinidae", "order": "Carcharhiniformes", "genus": "Carcharhinus", "yod": 1861 },
            { "name": "Hardnose Shark", "family": "Carcharhinidae", "order": "Carcharhiniformes", "genus": "Carcharhinus", "yod": 1839 },
            { "name": "Blacktip Reef Shark", "family": "Carcharhinidae", "order": "Carcharhiniformes", "genus": "Carcharhinus", "yod": 1824 },
            { "name": "Dusky Shark", "family": "Carcharhinidae", "order": "Carcharhiniformes", "genus": "Carcharhinus", "yod": 1818 },
            { "name": "Lost Shark", "family": "Carcharhinidae", "order": "Carcharhiniformes", "genus": "Carcharhinus", "yod": 2019 },
            { "name": "Caribbean Reef Shark", "family": "Carcharhinidae", "order": "Carcharhiniformes", "genus": "Carcharhinus", "yod": 1876 },
            { "name": "Sandbar Shark", "family": "Carcharhinidae", "order": "Carcharhiniformes", "genus": "Carcharhinus", "yod": 1827 },
            { "name": "Smalltail Shark", "family": "Carcharhinidae", "order": "Carcharhiniformes", "genus": "Carcharhinus", "yod": 1839 },
            { "name": "Blackspot Shark", "family": "Carcharhinidae", "order": "Carcharhiniformes", "genus": "Carcharhinus", "yod": 1913 },
            { "name": "Night Shark", "family": "Carcharhinidae", "order": "Carcharhiniformes", "genus": "Carcharhinus", "yod": 1868 },
            { "name": "Spottail Shark", "family": "Carcharhinidae", "order": "Carcharhiniformes", "genus": "Carcharhinus", "yod": 1839 },
            { "name": "Australian Blacktip Shark", "family": "Carcharhinidae", "order": "Carcharhiniformes", "genus": "Carcharhinus", "yod": 1950 },
            { "name": "Indonesian Whaler Shark", "family": "Carcharhinidae", "order": "Carcharhiniformes", "genus": "Carcharhinus", "yod": 1852 },
            { "name": "Tiger Shark", "family": "Carcharhinidae", "order": "Carcharhiniformes", "genus": "Galeocerdo", "yod": 1822 },
            { "name": "Ganges Shark", "family": "Carcharhinidae", "order": "Carcharhiniformes", "genus": "Glyphis", "yod": 1839 },
            { "name": "Northern River Shark", "family": "Carcharhinidae", "order": "Carcharhiniformes", "genus": "Glyphis", "yod": 2008 },
            { "name": "Speartooth Shark", "family": "Carcharhinidae", "order": "Carcharhiniformes", "genus": "Glyphis", "yod": 1839 },
            { "name": "Daggernose Shark", "family": "Carcharhinidae", "order": "Carcharhiniformes", "genus": "Isogomphodon", "yod": 1839 },
            { "name": "Broadfin Shark", "family": "Carcharhinidae", "order": "Carcharhiniformes", "genus": "Lamiopsis", "yod": 1839 },
            { "name": "Borneo Broadfin Shark", "family": "Carcharhinidae", "order": "Carcharhiniformes", "genus": "Lamiopsis", "yod": 1905 },
            { "name": "Sliteye Shark", "family": "Carcharhinidae", "order": "Carcharhiniformes", "genus": "Loxodon", "yod": 1839 },
            { "name": "Whitenose Shark", "family": "Carcharhinidae", "order": "Carcharhiniformes", "genus": "Nasolamia", "yod": 1898 },
            { "name": "Sicklefin Lemon Shark", "family": "Carcharhinidae", "order": "Carcharhiniformes", "genus": "Negaprion", "yod": 1837 },
            { "name": "Lemon Shark", "family": "Carcharhinidae", "order": "Carcharhiniformes", "genus": "Negaprion", "yod": 1868 },
            { "name": "Blue Shark", "family": "Carcharhinidae", "order": "Carcharhiniformes", "genus": "Prionace", "yod": 1758 },
            { "name": "Milk Shark", "family": "Carcharhinidae", "order": "Carcharhiniformes", "genus": "Rhizoprionodon", "yod": 1837 },
            { "name": "Brazilian Sharpnose Shark", "family": "Carcharhinidae", "order": "Carcharhiniformes", "genus": "Rhizoprionodon", "yod": 1839 },
            { "name": "Pacific Sharpnose Shark", "family": "Carcharhinidae", "order": "Carcharhiniformes", "genus": "Rhizoprionodon", "yod": 1882 },
            { "name": "Grey Sharpnose Shark", "family": "Carcharhinidae", "order": "Carcharhiniformes", "genus": "Rhizoprionodon", "yod": 1964 },
            { "name": "Caribbean Sharpnose Shark", "family": "Carcharhinidae", "order": "Carcharhiniformes", "genus": "Rhizoprionodon", "yod": 1861 },
            { "name": "Australian Sharpnose Shark", "family": "Carcharhinidae", "order": "Carcharhiniformes", "genus": "Rhizoprionodon", "yod": 1915 },
            { "name": "Atlantic Sharpnose Shark", "family": "Carcharhinidae", "order": "Carcharhiniformes", "genus": "Rhizoprionodon", "yod": 1836 },
            { "name": "Spadenose Shark", "family": "Carcharhinidae", "order": "Carcharhiniformes", "genus": "Scoliodon", "yod": 1838 },
            { "name": "Pacific Spadenose Shark", "family": "Carcharhinidae", "order": "Carcharhiniformes", "genus": "Scoliodon", "yod": 1852 },
            { "name": "Whitetip Reef Shark", "family": "Carcharhinidae", "order": "Carcharhiniformes", "genus": "Triaenodon", "yod": 1837 },
            { "name": "Hooktooth Shark", "family": "Hemigaleidae", "order": "Carcharhiniformes", "genus": "Chaenogaleus", "yod": 1852 },
            { "name": "Australian Weasel Shark", "family": "Hemigaleidae", "order": "Carcharhiniformes", "genus": "Hemigaleus", "yod": 2005 },
            { "name": "Sicklefin Weasel Shark", "family": "Hemigaleidae", "order": "Carcharhiniformes", "genus": "Hemigaleus", "yod": 1852 },
            { "name": "Snaggletooth Shark", "family": "Hemigaleidae", "order": "Carcharhiniformes", "genus": "Hemipristis", "yod": 1871 },
            { "name": "Whitetip Weasel Shark", "family": "Hemigaleidae", "order": "Carcharhiniformes", "genus": "Paragaleus", "yod": 1985 },
            { "name": "Atlantic Weasel Shark", "family": "Hemigaleidae", "order": "Carcharhiniformes", "genus": "Paragaleus", "yod": 1906 },
            { "name": "Slender Weasel Shark", "family": "Hemigaleidae", "order": "Carcharhiniformes", "genus": "Paragaleus", "yod": 1996 },
            { "name": "Straighttooth Weasel Shark", "family": "Hemigaleidae", "order": "Carcharhiniformes", "genus": "Paragaleus", "yod": 1963 },
            { "name": "Barbeled Houndshark", "family": "Leptochariidae", "order": "Carcharhiniformes", "genus": "Leptocharias", "yod": 1839 },
            { "name": "White-bodied Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Apristurus", "yod": 1999 },
            { "name": "Rough-skin Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Apristurus", "yod": 2008 },
            { "name": "White Ghost Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Apristurus", "yod": 1998 },
            { "name": "Pinocchio Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Apristurus", "yod": 2008 },
            { "name": "Short-belly Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Apristurus", "yod": 2014 },
            { "name": "Brown Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Apristurus", "yod": 1892 },
            { "name": "Bighead Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Apristurus", "yod": 2008 },
            { "name": "Hoary Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Apristurus", "yod": 1979 },
            { "name": "Flaccid Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Apristurus", "yod": 1999 },
            { "name": "Fedorov's Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Apristurus", "yod": 1985 },
            { "name": "Garrick's Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Apristurus", "yod": 2013 },
            { "name": "Humpback Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Apristurus", "yod": 1985 },
            { "name": "Longfin Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Apristurus", "yod": 1934 },
            { "name": "Smallbelly Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Apristurus", "yod": 1906 },
            { "name": "Shortnose Demon Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Apristurus", "yod": 1988 },
            { "name": "Broadnose Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Apristurus", "yod": 1962 },
            { "name": "Japanese Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Apristurus", "yod": 1975 },
            { "name": "Longnose Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Apristurus", "yod": 1972 },
            { "name": "Iceland Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Apristurus", "yod": 1922 },
            { "name": "Longhead Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Apristurus", "yod": 1975 },
            { "name": "Flathead Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Apristurus", "yod": 1909 },
            { "name": "Broadmouth Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Apristurus", "yod": 1985 },
            { "name": "Ghost Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Apristurus", "yod": 1979 },
            { "name": "Manocherian's Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Apristurus", "yod": 2021 },
            { "name": "Black Roughscale Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Apristurus", "yod": 2004 },
            { "name": "Smalleye Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Apristurus", "yod": 1922 },
            { "name": "Small-dorsal Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Apristurus", "yod": 1986 },
            { "name": "Milkeye Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Apristurus", "yod": 2013 },
            { "name": "Largenose Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Apristurus", "yod": 1959 },
            { "name": "Ridge-egg Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Apristurus", "yod": 2023 },
            { "name": "Smallfin Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Apristurus", "yod": 1979 },
            { "name": "Fat Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Apristurus", "yod": 1983 },
            { "name": "Borneo Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Apristurus", "yod": 1909 },
            { "name": "Deepwater Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Apristurus", "yod": 1896 },
            { "name": "Broadgill Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Apristurus", "yod": 1944 },
            { "name": "Saldanha Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Apristurus", "yod": 1925 },
            { "name": "Pale Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Apristurus", "yod": 1913 },
            { "name": "South China Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Apristurus", "yod": 1981 },
            { "name": "Spongehead Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Apristurus", "yod": 1905 },
            { "name": "Panama Ghost Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Apristurus", "yod": 1979 },
            { "name": "Yang's Longnose Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Apristurus", "yod": 2017 },
            { "name": "Australian Spotted Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Asymbolus", "yod": 1885 },
            { "name": "Blotched Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Asymbolus", "yod": 1999 },
            { "name": "Starry Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Asymbolus", "yod": 2008 },
            { "name": "Western Spotted Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Asymbolus", "yod": 1999 },
            { "name": "Pale-spotted Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Asymbolus", "yod": 1999 },
            { "name": "Dwarf Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Asymbolus", "yod": 1999 },
            { "name": "Orange-spotted Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Asymbolus", "yod": 1999 },
            { "name": "Variegated Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Asymbolus", "yod": 1999 },
            { "name": "Gulf Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Asymbolus", "yod": 1908 },
            { "name": "Arabian Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Bythaelurus", "yod": 1913 },
            { "name": "Bach's Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Bythaelurus", "yod": 2016 },
            { "name": "Dusky Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Bythaelurus", "yod": 1878 },
            { "name": "Broadhead Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Bythaelurus", "yod": 1987 },
            { "name": "New Zealand Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Bythaelurus", "yod": 1971 },
            { "name": "Jaguar Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Bythaelurus", "yod": 2012 },
            { "name": "Bristly Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Bythaelurus", "yod": 1891 },
            { "name": "Spotless Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Bythaelurus", "yod": 1982 },
            { "name": "Sombre Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Bythaelurus", "yod": 2008 },
            { "name": "Mud Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Bythaelurus", "yod": 1972 },
            { "name": "Duskysnout Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Bythaelurus", "yod": 2015 },
            { "name": "Narrowhead Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Bythaelurus", "yod": 2015 },
            { "name": "Error Seamount Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Bythaelurus", "yod": 2018 },
            { "name": "Vivaldi's Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Bythaelurus", "yod": 2017 },
            { "name": "Lollipop Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Cephalurus", "yod": 1892 },
            { "name": "Australian Sawtail Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Figaro", "yod": 1928 },
            { "name": "Northern Sawtail Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Figaro", "yod": 2008 },
            { "name": "Antilles Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Galeus", "yod": 1979 },
            { "name": "Roughtail Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Galeus", "yod": 1927 },
            { "name": "Atlantic Sawtail Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Galeus", "yod": 1888 },
            { "name": "Longfin Sawtail Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Galeus", "yod": 1966 },
            { "name": "Gecko Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Galeus", "yod": 1904 },
            { "name": "Philippines Sawtail Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Galeus", "yod": 2022 },
            { "name": "Slender Sawtail Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Galeus", "yod": 1993 },
            { "name": "Longnose Sawtail Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Galeus", "yod": 1987 },
            { "name": "Blackmouth Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Galeus", "yod": 1810 },
            { "name": "Southern Sawtail Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Galeus", "yod": 2001 },
            { "name": "Mouse Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Galeus", "yod": 1904 },
            { "name": "Broadfin Sawtail Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Galeus", "yod": 1975 },
            { "name": "Peppered Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Galeus", "yod": 1966 },
            { "name": "African Sawtail Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Galeus", "yod": 1959 },
            { "name": "Phallic Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Galeus", "yod": 2008 },
            { "name": "Blacktip Sawtail Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Galeus", "yod": 1909 },
            { "name": "Dwarf Sawtail Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Galeus", "yod": 1979 },
            { "name": "Springer's Sawtail Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Galeus", "yod": 1998 },
            { "name": "Speckled Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Halaelurus", "yod": 1972 },
            { "name": "Blackspotted Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Halaelurus", "yod": 1838 },
            { "name": "Lined Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Halaelurus", "yod": 1975 },
            { "name": "Indonesian Speckled Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Halaelurus", "yod": 2007 },
            { "name": "Tiger Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Halaelurus", "yod": 1904 },
            { "name": "Quagga Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Halaelurus", "yod": 1899 },
            { "name": "Rusty Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Halaelurus", "yod": 2007 },
            { "name": "Puffadder Shyshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Haploblepharus", "yod": 1822 },
            { "name": "Brown Shyshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Haploblepharus", "yod": 1950 },
            { "name": "Natal Shyshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Haploblepharus", "yod": 2006 },
            { "name": "Dark Shyshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Haploblepharus", "yod": 1838 },
            { "name": "Honeycomb Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Holohalaelurus", "yod": 2006 },
            { "name": "Grinning Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Holohalaelurus", "yod": 2006 },
            { "name": "Crying Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Holohalaelurus", "yod": 1939 },
            { "name": "Whitespotted Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Holohalaelurus", "yod": 1914 },
            { "name": "Izak Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Holohalaelurus", "yod": 1922 },
            { "name": "White-clasper Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Parmaturus", "yod": 2007 },
            { "name": "Campeche Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Parmaturus", "yod": 1979 },
            { "name": "Velvet Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Parmaturus", "yod": 2007 },
            { "name": "McMillan's Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Parmaturus", "yod": 1985 },
            { "name": "Salamander Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Parmaturus", "yod": 1906 },
            { "name": "Filetail Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Parmaturus", "yod": 1892 },
            { "name": "Onefin Catshark", "family": "Pentanchidae", "order": "Carcharhiniformes", "genus": "Pentanchus", "yod": 1912 },
            { "name": "Harlequin Catshark", "family": "Proscylliidae", "order": "Carcharhiniformes", "genus": "Ctenacis", "yod": 1968 },
            { "name": "Cuban Ribbontail Catshark", "family": "Proscylliidae", "order": "Carcharhiniformes", "genus": "Eridacnis", "yod": 1944 },
            { "name": "Pygmy Ribbontail Catshark", "family": "Proscylliidae", "order": "Carcharhiniformes", "genus": "Eridacnis", "yod": 1913 },
            { "name": "African Ribbontail Catshark", "family": "Proscylliidae", "order": "Carcharhiniformes", "genus": "Eridacnis", "yod": 1957 },
            { "name": "Graceful Catshark", "family": "Proscylliidae", "order": "Carcharhiniformes", "genus": "Proscyllium", "yod": 1904 },
            { "name": "Magnificent Catshark", "family": "Proscylliidae", "order": "Carcharhiniformes", "genus": "Proscyllium", "yod": 2004 },
            { "name": "Slender Smoothhound", "family": "Pseudotriakidae", "order": "Carcharhiniformes", "genus": "Gollum", "yod": 1954 },
            { "name": "Sulu Gollumshark", "family": "Pseudotriakidae", "order": "Carcharhiniformes", "genus": "Gollum", "yod": 2011 },
            { "name": "Dwarf False Catshark", "family": "Pseudotriakidae", "order": "Carcharhiniformes", "genus": "Planonasus", "yod": 2013 },
            { "name": "False Catshark", "family": "Pseudotriakidae", "order": "Carcharhiniformes", "genus": "Pseudotriakis", "yod": 1868 },
            { "name": "Bali Catshark", "family": "Scyliorhinidae", "order": "Carcharhiniformes", "genus": "Atelomycterus", "yod": 2005 },
            { "name": "Spotted-belly Catshark", "family": "Scyliorhinidae", "order": "Carcharhiniformes", "genus": "Atelomycterus", "yod": 2015 },
            { "name": "Banded Sand Catshark", "family": "Scyliorhinidae", "order": "Carcharhiniformes", "genus": "Atelomycterus", "yod": 1993 },
            { "name": "Australian Marbled Catshark", "family": "Scyliorhinidae", "order": "Carcharhiniformes", "genus": "Atelomycterus", "yod": 1939 },
            { "name": "Coral Catshark", "family": "Scyliorhinidae", "order": "Carcharhiniformes", "genus": "Atelomycterus", "yod": 1830 },
            { "name": "Eastern Banded Catshark", "family": "Scyliorhinidae", "order": "Carcharhiniformes", "genus": "Atelomycterus", "yod": 2007 },
            { "name": "Kanakorum Catshark", "family": "Scyliorhinidae", "order": "Carcharhiniformes", "genus": "Aulohalaelurus", "yod": 1990 },
            { "name": "Australian Black-spotted Catshark", "family": "Scyliorhinidae", "order": "Carcharhiniformes", "genus": "Aulohalaelurus", "yod": 1905 },
            { "name": "Whitefin Swellshark", "family": "Scyliorhinidae", "order": "Carcharhiniformes", "genus": "Cephaloscyllium", "yod": 2008 },
            { "name": "Cook's Swellshark", "family": "Scyliorhinidae", "order": "Carcharhiniformes", "genus": "Cephaloscyllium", "yod": 2008 },
            { "name": "Reticulated Swellshark", "family": "Scyliorhinidae", "order": "Carcharhiniformes", "genus": "Cephaloscyllium", "yod": 1966 },
            { "name": "Formosa Swellshark", "family": "Scyliorhinidae", "order": "Carcharhiniformes", "genus": "Cephaloscyllium", "yod": 1962 },
            { "name": "Australian Reticulated Swellshark", "family": "Scyliorhinidae", "order": "Carcharhiniformes", "genus": "Cephaloscyllium", "yod": 2008 },
            { "name": "Draughtsboard Shark", "family": "Scyliorhinidae", "order": "Carcharhiniformes", "genus": "Cephaloscyllium", "yod": 1788 },
            { "name": "Australian Swellshark", "family": "Scyliorhinidae", "order": "Carcharhiniformes", "genus": "Cephaloscyllium", "yod": 1853 },
            { "name": "Painted Swellshark", "family": "Scyliorhinidae", "order": "Carcharhiniformes", "genus": "Cephaloscyllium", "yod": 2008 },
            { "name": "Sarawak Pygmy Swellshark", "family": "Scyliorhinidae", "order": "Carcharhiniformes", "genus": "Cephaloscyllium", "yod": 2005 },
            { "name": "Flagtail Swellshark", "family": "Scyliorhinidae", "order": "Carcharhiniformes", "genus": "Cephaloscyllium", "yod": 2008 },
            { "name": "Indian Swellshark", "family": "Scyliorhinidae", "order": "Carcharhiniformes", "genus": "Cephaloscyllium", "yod": 1974 },
            { "name": "Speckled Swellshark", "family": "Scyliorhinidae", "order": "Carcharhiniformes", "genus": "Cephaloscyllium", "yod": 2008 },
            { "name": "Steven's Swellshark", "family": "Scyliorhinidae", "order": "Carcharhiniformes", "genus": "Cephaloscyllium", "yod": 2011 },
            { "name": "Balloon Shark", "family": "Scyliorhinidae", "order": "Carcharhiniformes", "genus": "Cephaloscyllium", "yod": 1921 },
            { "name": "Blotchy Swellshark", "family": "Scyliorhinidae", "order": "Carcharhiniformes", "genus": "Cephaloscyllium", "yod": 1903 },
            { "name": "Saddled Swellshark", "family": "Scyliorhinidae", "order": "Carcharhiniformes", "genus": "Cephaloscyllium", "yod": 2008 },
            { "name": "Swellshark", "family": "Scyliorhinidae", "order": "Carcharhiniformes", "genus": "Cephaloscyllium", "yod": 1880 },
            { "name": "Narrow-bar Swellshark", "family": "Scyliorhinidae", "order": "Carcharhiniformes", "genus": "Cephaloscyllium", "yod": 2008 },
            { "name": "Striped Catshark", "family": "Scyliorhinidae", "order": "Carcharhiniformes", "genus": "Poroderma", "yod": 1789 },
            { "name": "Leopard Catshark", "family": "Scyliorhinidae", "order": "Carcharhiniformes", "genus": "Poroderma", "yod": 1838 },
            { "name": "Narrowmouth Catshark", "family": "Scyliorhinidae", "order": "Carcharhiniformes", "genus": "Schroederichthys", "yod": 1838 },
            { "name": "Red-spotted Catshark", "family": "Scyliorhinidae", "order": "Carcharhiniformes", "genus": "Schroederichthys", "yod": 1848 },
            { "name": "Narrowtail Catshark", "family": "Scyliorhinidae", "order": "Carcharhiniformes", "genus": "Schroederichthys", "yod": 1966 },
            { "name": "Lizard Catshark", "family": "Scyliorhinidae", "order": "Carcharhiniformes", "genus": "Schroederichthys", "yod": 2001 },
            { "name": "Slender Catshark", "family": "Scyliorhinidae", "order": "Carcharhiniformes", "genus": "Schroederichthys", "yod": 1966 },
            { "name": "Boa Catshark", "family": "Scyliorhinidae", "order": "Carcharhiniformes", "genus": "Scyliorhinus", "yod": 1896 },
            { "name": "Smallspotted Catshark", "family": "Scyliorhinidae", "order": "Carcharhiniformes", "genus": "Scyliorhinus", "yod": 1758 },
            { "name": "Yellowspotted Catshark", "family": "Scyliorhinidae", "order": "Carcharhiniformes", "genus": "Scyliorhinus", "yod": 1838 },
            { "name": "West African Catshark", "family": "Scyliorhinidae", "order": "Carcharhiniformes", "genus": "Scyliorhinus", "yod": 1970 },
            { "name": "Comoro Catshark", "family": "Scyliorhinidae", "order": "Carcharhiniformes", "genus": "Scyliorhinus", "yod": 1988 },
            { "name": "Brownspotted Catshark", "family": "Scyliorhinidae", "order": "Carcharhiniformes", "genus": "Scyliorhinus", "yod": 1934 },
            { "name": "Freckled Catshark", "family": "Scyliorhinidae", "order": "Carcharhiniformes", "genus": "Scyliorhinus", "yod": 1907 },
            { "name": "Whitesaddled Catshark", "family": "Scyliorhinidae", "order": "Carcharhiniformes", "genus": "Scyliorhinus", "yod": 1966 },
            { "name": "Blotched Catshark", "family": "Scyliorhinidae", "order": "Carcharhiniformes", "genus": "Scyliorhinus", "yod": 1966 },
            { "name": "Chain Catshark", "family": "Scyliorhinidae", "order": "Carcharhiniformes", "genus": "Scyliorhinus", "yod": 1881 },
            { "name": "Nursehound", "family": "Scyliorhinidae", "order": "Carcharhiniformes", "genus": "Scyliorhinus", "yod": 1758 },
            { "name": "Izu Catshark", "family": "Scyliorhinidae", "order": "Carcharhiniformes", "genus": "Scyliorhinus", "yod": 1992 },
            { "name": "Cloudy Catshark", "family": "Scyliorhinidae", "order": "Carcharhiniformes", "genus": "Scyliorhinus", "yod": 1908 },
            { "name": "Dwarf Catshark", "family": "Scyliorhinidae", "order": "Carcharhiniformes", "genus": "Scyliorhinus", "yod": 1936 },
            { "name": "Dark-freckled Catshark", "family": "Scyliorhinidae", "order": "Carcharhiniformes", "genus": "Scyliorhinus", "yod": 2015 },
            { "name": "Winghead Shark", "family": "Sphyrnidae", "order": "Carcharhiniformes", "genus": "Eusphyra", "yod": 1816 },
            { "name": "Shovelbill Shark", "family": "Sphyrnidae", "order": "Carcharhiniformes", "genus": "Sphyrna", "yod": 2024 },
            { "name": "Scalloped Bonnethead", "family": "Sphyrnidae", "order": "Carcharhiniformes", "genus": "Sphyrna", "yod": 1940 },
            { "name": "Carolina Hammerhead", "family": "Sphyrnidae", "order": "Carcharhiniformes", "genus": "Sphyrna", "yod": 2013 },
            { "name": "Scalloped Hammerhead", "family": "Sphyrnidae", "order": "Carcharhiniformes", "genus": "Sphyrna", "yod": 1834 },
            { "name": "Scoophead Hammerhead", "family": "Sphyrnidae", "order": "Carcharhiniformes", "genus": "Sphyrna", "yod": 1940 },
            { "name": "Great Hammerhead", "family": "Sphyrnidae", "order": "Carcharhiniformes", "genus": "Sphyrna", "yod": 1837 },
            { "name": "Bonnethead Shark", "family": "Sphyrnidae", "order": "Carcharhiniformes", "genus": "Sphyrna", "yod": 1758 },
            { "name": "Smalleye Hammerhead", "family": "Sphyrnidae", "order": "Carcharhiniformes", "genus": "Sphyrna", "yod": 1822 },
            { "name": "Smooth Hammerhead", "family": "Sphyrnidae", "order": "Carcharhiniformes", "genus": "Sphyrna", "yod": 1758 },
            { "name": "Whiskery Shark", "family": "Triakidae", "order": "Carcharhiniformes", "genus": "Furgaleus", "yod": 1943 },
            { "name": "Tope Shark", "family": "Triakidae", "order": "Carcharhiniformes", "genus": "Galeorhinus", "yod": 1758 },
            { "name": "Sailback Houndshark", "family": "Triakidae", "order": "Carcharhiniformes", "genus": "Gogolia", "yod": 1973 },
            { "name": "Deepwater Sicklefin Houndshark", "family": "Triakidae", "order": "Carcharhiniformes", "genus": "Hemitriakis", "yod": 1993 },
            { "name": "Ocellated Topeshark", "family": "Triakidae", "order": "Carcharhiniformes", "genus": "Hemitriakis", "yod": 2004 },
            { "name": "Sicklefin Houndshark", "family": "Triakidae", "order": "Carcharhiniformes", "genus": "Hemitriakis", "yod": 1993 },
            { "name": "Indonesian Houndshark", "family": "Triakidae", "order": "Carcharhiniformes", "genus": "Hemitriakis", "yod": 2009 },
            { "name": "Japanese Topeshark", "family": "Triakidae", "order": "Carcharhiniformes", "genus": "Hemitriakis", "yod": 1839 },
            { "name": "Whitefin Topeshark", "family": "Triakidae", "order": "Carcharhiniformes", "genus": "Hemitriakis", "yod": 1923 },
            { "name": "Blacktip Tope", "family": "Triakidae", "order": "Carcharhiniformes", "genus": "Hypogaleus", "yod": 1939 },
            { "name": "Longnose Houndshark", "family": "Triakidae", "order": "Carcharhiniformes", "genus": "Iago", "yod": 1979 },
            { "name": "Bigeye Houndshark", "family": "Triakidae", "order": "Carcharhiniformes", "genus": "Iago", "yod": 1939 },
            { "name": "Andaman Smoothhound", "family": "Triakidae", "order": "Carcharhiniformes", "genus": "Mustelus", "yod": 2021 },
            { "name": "Whitemargin Fin Houndshark", "family": "Triakidae", "order": "Carcharhiniformes", "genus": "Mustelus", "yod": 2005 },
            { "name": "Gummy Shark", "family": "Triakidae", "order": "Carcharhiniformes", "genus": "Mustelus", "yod": 1870 },
            { "name": "Starry Smoothhound", "family": "Triakidae", "order": "Carcharhiniformes", "genus": "Mustelus", "yod": 1821 },
            { "name": "Grey Smoothhound", "family": "Triakidae", "order": "Carcharhiniformes", "genus": "Mustelus", "yod": 1864 },
            { "name": "Dusky Smoothhound", "family": "Triakidae", "order": "Carcharhiniformes", "genus": "Mustelus", "yod": 1815 },
            { "name": "Caribbean Smoothhound", "family": "Triakidae", "order": "Carcharhiniformes", "genus": "Mustelus", "yod": 1997 },
            { "name": "Sharptooth Smoothhound", "family": "Triakidae", "order": "Carcharhiniformes", "genus": "Mustelus", "yod": 1864 },
            { "name": "Striped Smoothhound", "family": "Triakidae", "order": "Carcharhiniformes", "genus": "Mustelus", "yod": 1913 },
            { "name": "Spotless Smoothhound", "family": "Triakidae", "order": "Carcharhiniformes", "genus": "Mustelus", "yod": 1908 },
            { "name": "Brown Smoothhound", "family": "Triakidae", "order": "Carcharhiniformes", "genus": "Mustelus", "yod": 1863 },
            { "name": "Smalleye Smoothhound", "family": "Triakidae", "order": "Carcharhiniformes", "genus": "Mustelus", "yod": 1963 },
            { "name": "Spotted Estuary Smoothhound", "family": "Triakidae", "order": "Carcharhiniformes", "genus": "Mustelus", "yod": 1932 },
            { "name": "Sicklefin Smoothhound", "family": "Triakidae", "order": "Carcharhiniformes", "genus": "Mustelus", "yod": 1882 },
            { "name": "Starspotted Smoothhound", "family": "Triakidae", "order": "Carcharhiniformes", "genus": "Mustelus", "yod": 1854 },
            { "name": "Mangalore Houndshark", "family": "Triakidae", "order": "Carcharhiniformes", "genus": "Mustelus", "yod": 2011 },
            { "name": "Speckled Smoothhound", "family": "Triakidae", "order": "Carcharhiniformes", "genus": "Mustelus", "yod": 1877 },
            { "name": "Dwarf Smoothhound", "family": "Triakidae", "order": "Carcharhiniformes", "genus": "Mustelus", "yod": 1997 },
            { "name": "Arabian Smoothhound", "family": "Triakidae", "order": "Carcharhiniformes", "genus": "Mustelus", "yod": 1899 },
            { "name": "Common Smoothhound", "family": "Triakidae", "order": "Carcharhiniformes", "genus": "Mustelus", "yod": 1758 },
            { "name": "Narrowfin Smoothhound", "family": "Triakidae", "order": "Carcharhiniformes", "genus": "Mustelus", "yod": 1939 },
            { "name": "Whitespotted Smoothhound", "family": "Triakidae", "order": "Carcharhiniformes", "genus": "Mustelus", "yod": 1957 },
            { "name": "Blackspotted Smoothhound", "family": "Triakidae", "order": "Carcharhiniformes", "genus": "Mustelus", "yod": 1827 },
            { "name": "Australian Grey Smoothhound", "family": "Triakidae", "order": "Carcharhiniformes", "genus": "Mustelus", "yod": 2006 },
            { "name": "Western Spotted Gummy Shark", "family": "Triakidae", "order": "Carcharhiniformes", "genus": "Mustelus", "yod": 2008 },
            { "name": "Eastern Spotted Gummy Shark", "family": "Triakidae", "order": "Carcharhiniformes", "genus": "Mustelus", "yod": 2008 },
            { "name": "Humpback Smoothhound", "family": "Triakidae", "order": "Carcharhiniformes", "genus": "Mustelus", "yod": 1973 },
            { "name": "Whitefin Smoothhound", "family": "Triakidae", "order": "Carcharhiniformes", "genus": "Mustelus", "yod": 2006 },
            { "name": "Flapnose Houndshark", "family": "Triakidae", "order": "Carcharhiniformes", "genus": "Scylliogaleus", "yod": 1902 },
            { "name": "Sharpfin Houndshark", "family": "Triakidae", "order": "Carcharhiniformes", "genus": "Triakis", "yod": 1968 },
            { "name": "Spotted Houndshark", "family": "Triakidae", "order": "Carcharhiniformes", "genus": "Triakis", "yod": 1867 },
            { "name": "Sharptooth Houndshark", "family": "Triakidae", "order": "Carcharhiniformes", "genus": "Triakis", "yod": 1839 },
            { "name": "Banded Houndshark", "family": "Triakidae", "order": "Carcharhiniformes", "genus": "Triakis", "yod": 1839 },
            { "name": "Leopard Shark", "family": "Triakidae", "order": "Carcharhiniformes", "genus": "Triakis", "yod": 1855 },
        ];

window.sharks = sharks;
